# Generated by Django 4.2 on 2023-04-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="car",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("model", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
                ("factory_year", models.IntegerField()),
                ("model_year", models.IntegerField()),
                ("value", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
